sudo: required
services:
  - docker


before_install:
  - docker build -t ravendraksingh/docker-react -f Dockerfile.dev .

script:
  #- docker run ravendraksingh/docker-react npm run test -- --coverage
  - docker run -e CI=true ravendraksingh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"  
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-612879991665"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  
